name: Publish
on:
  # push:
  #   branches:
  #     - release

  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    # TODO: A potential idea here would be to walk the libs hierarchy and only publish the packages that have newer versions specified than what is already published.
    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        working-directory: libs/ts/date
        run: npx jsr publish
        