name: Publish
on:
  # push:
  #   branches:
  #     - release

  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    # TODO: A potential idea here would be to walk the libs hierarchy and only publish the packages that have newer versions specified than what is already published.
    steps:
      - uses: actions/checkout@v4

      - name: Publish libs/ts/assert-never
        working-directory: libs/ts/assert-never
        run: deno run --allow-read --allow-net ../jsr-metadata/local-version-is-newer.deno.ts && npx jsr publish
        
      - name: Publish libs/ts/date
        working-directory: libs/ts/date
        run: deno run --allow-read --allow-net ../jsr-metadata/local-version-is-newer.deno.ts && npx jsr publish
        
      - name: Publish libs/ts/detect-runtime
        working-directory: libs/ts/detect-runtime
        run: deno run --allow-read --allow-net ../jsr-metadata/local-version-is-newer.deno.ts && npx jsr publish
        