name: Publish
on:
  # push:
  #   branches:
  #     - release

  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    # TODO: A potential idea here would be to walk the libs hierarchy and only publish the packages that have newer versions specified than what is already published.
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - uses: oven-sh/setup-bun@v1

      - run: bun install

      - name: Publish libs/ts/assert-never if needed...
        working-directory: libs/ts/assert-never
        run: deno run --allow-read --allow-net --allow-run ../jsr-metadata/publish-if-local-version-is-newer.deno.ts
        
      - name: Publish libs/ts/date if needed...
        working-directory: libs/ts/date
        run: deno run --allow-read --allow-net --allow-run ../jsr-metadata/publish-if-local-version-is-newer.deno.ts
        
      - name: Publish libs/ts/detect-runtime if needed...
        working-directory: libs/ts/detect-runtime
        run: deno run --allow-read --allow-net --allow-run ../jsr-metadata/publish-if-local-version-is-newer.deno.ts
        